#!/usr/bin/env node
// Writes public/env.js from .env.local (or the process environment).
//
//   npm run env:build
//
// Only browser-safe values are copied. The kiosk is a public web page: whatever
// lands in env.js is readable by anyone who opens its URL, so the allow-list
// below is deliberately short and the service-role key is rejected outright.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const outfile = path.join(root, 'public', 'env.js');

// Each entry is [browser key, ...source names in priority order].
const PUBLIC_KEYS = [
  ['SUPABASE_URL', 'SUPABASE_URL', 'VITE_PUBLIC_SUPABASE_URL', 'VITE_SUPABASE_URL'],
  [
    'SUPABASE_ANON_KEY',
    'SUPABASE_ANON_KEY',
    'VITE_PUBLIC_SUPABASE_ANON_KEY',
    'VITE_SUPABASE_ANON_KEY',
    // Read last, and only so the service-role check below can explain itself:
    // this repo's .env.local currently holds a service-role key under this name.
    'VITE_PUBLIC_SUPABASE_PUBLISHABLE_KEY'
  ],
  ['ZDRAVO_EMAIL_ENDPOINT', 'ZDRAVO_EMAIL_ENDPOINT'],
  ['ZDRAVO_RECIPE_IMAGE_BUCKET', 'ZDRAVO_RECIPE_IMAGE_BUCKET'],
  ['ZDRAVO_INGREDIENT_IMAGE_BUCKET', 'ZDRAVO_INGREDIENT_IMAGE_BUCKET'],
  ['ZDRAVO_IMAGE_CDN_BASE_URL', 'ZDRAVO_IMAGE_CDN_BASE_URL'],
  ['ZDRAVO_PUBLIC_RECIPE_AUTO_DOWNLOAD', 'ZDRAVO_PUBLIC_RECIPE_AUTO_DOWNLOAD'],
  ['ZDRAVO_REFRESH_INTERVAL_MS', 'ZDRAVO_REFRESH_INTERVAL_MS']
];

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  return fs.readFileSync(filePath, 'utf8').split(/\r?\n/).reduce((values, line) => {
    const trimmed = line.trim();
    const separatorIndex = trimmed.indexOf('=');

    if (!trimmed || trimmed.startsWith('#') || separatorIndex === -1) {
      return values;
    }

    const key = trimmed.slice(0, separatorIndex).trim();
    values[key] = trimmed.slice(separatorIndex + 1).trim().replace(/^['"]|['"]$/g, '');

    return values;
  }, {});
}

function jwtRole(value) {
  try {
    return JSON.parse(Buffer.from(String(value).split('.')[1], 'base64').toString()).role || '';
  } catch (error) {
    return '';
  }
}

const fileValues = {
  ...parseEnvFile(path.join(root, '.env')),
  ...parseEnvFile(path.join(root, '.env.local'))
};

const values = {};

PUBLIC_KEYS.forEach(([browserKey, ...sources]) => {
  const value = sources
    .map((name) => process.env[name] || fileValues[name])
    .find((candidate) => String(candidate || '').trim());

  if (value) {
    values[browserKey] = String(value).trim();
  }
});

const anonKey = values.SUPABASE_ANON_KEY || '';

if (anonKey && jwtRole(anonKey) === 'service_role') {
  console.error(
    'Refusing to write public/env.js: the configured Supabase key is a service_role key.\n' +
    'That key grants full read/write access to the database and would be public in the\n' +
    'browser bundle. Set SUPABASE_ANON_KEY in .env.local to the project\'s anon /\n' +
    'publishable key (Supabase dashboard -> Project Settings -> API Keys).'
  );
  process.exit(1);
}

const missing = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'].filter((key) => !values[key]);

if (missing.length) {
  console.error(
    `Missing required configuration: ${missing.join(', ')}.\n` +
    'Add them to .env.local (see .env.example) and run `npm run env:build` again.'
  );
  process.exit(1);
}

const banner = [
  '// Generated by scripts/build-env.cjs — do not edit, do not commit.',
  '// Public configuration only; see the script for the allow-list.',
  ''
].join('\n');

// A JWT's signature cannot be checked locally, so the only way to know the key
// works is to use it. Doing that here turns a kiosk that boots to an error
// screen into a build that fails with the reason.
async function verifyKey() {
  const url = `${values.SUPABASE_URL.replace(/\/+$/, '')}/rest/v1/recipes?select=id&limit=1`;

  let response;

  try {
    response = await fetch(url, {
      headers: { apikey: anonKey, authorization: `Bearer ${anonKey}` }
    });
  } catch (error) {
    console.warn(`Could not reach Supabase to verify the key (${error.message}); writing anyway.`);
    return true;
  }

  if (response.ok) {
    return true;
  }

  const detail = await response.text().catch(() => '');

  console.error(
    `Supabase rejected the configured key (HTTP ${response.status}).\n${detail}\n\n` +
      'Copy the key from the Supabase dashboard -> Project Settings -> API Keys ->\n' +
      '"anon public", and set it as SUPABASE_ANON_KEY in .env.local. A key cannot be\n' +
      'produced by editing the role inside another key: changing the payload\n' +
      'invalidates the signature.'
  );

  return false;
}

verifyKey().then((ok) => {
  if (!ok) {
    process.exit(1);
  }

  fs.writeFileSync(outfile, `${banner}window.__ZDRAVO_ENV__ = ${JSON.stringify(values, null, 2)};\n`, 'utf8');
  console.log(`Wrote ${path.relative(root, outfile)} with: ${Object.keys(values).join(', ')}`);
  console.log('Verified the anon key against Supabase.');
});
